"""Add FeedbackRequest model

Revision ID: e3f9d38b524e
Revises: e80a28d21668
Create Date: 2024-11-17 19:18:01.323943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f9d38b524e'
down_revision = 'e80a28d21668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('request_recipient', sa.String(length=80), nullable=False),
    sa.Column('recipient_email', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('unique_link', sa.String(length=200), nullable=True),
    sa.Column('session_data', sa.Text(), nullable=True),
    sa.Column('feedback_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['requestor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_request')
    # ### end Alembic commands ###
